import {
  type CardChoice,
  type CardCombatState,
  createCardCombatState,
  drawHand,
  resolveChoices,
} from "./cardCombat";
import type { Deck } from "./cards";

export interface CombatPolicy {
  choose(state: CardCombatState, hand: Deck, ownHp: number): CardChoice[];
}

// Greedy policy: attacks with every drawn card; switches to defend bottom face when own HP < 50.
// The threshold of 50 equals half the standard 100-HP starting squad (i.e. "below 50%").
export const GreedyPolicy: CombatPolicy = {
  choose(_state: CardCombatState, hand: Deck, ownHp: number): CardChoice[] {
    const lowHp = ownHp < 50;
    return hand.map((card) => ({
      cardId: card.id,
      face: lowHp && card.bottom.type === "defend" ? "bottom" : "top",
    }));
  },
};

const MAX_TURNS = 100;

// Runs a card-combat battle to completion using `policy` for both sides.
// Enemy intents are generated by the policy (overriding the default in drawHand) so that
// both player and enemy make deterministic, policy-driven decisions each turn.
export function simulateCardBattle(
  playerDeck: Deck,
  enemyDeck: Deck,
  playerHp: number,
  enemyHp: number,
  policy: CombatPolicy,
): CardCombatState {
  let state = createCardCombatState(playerDeck, enemyDeck, playerHp, enemyHp);
  let turns = 0;

  while (!state.isComplete && turns < MAX_TURNS) {
    state = drawHand(state);

    const enemyIntents = policy.choose(state, state.enemyHand, state.enemySquadHp);
    state = { ...state, enemyIntents };

    const playerChoices = policy.choose(state, state.playerHand, state.playerSquadHp);
    state = resolveChoices(state, playerChoices);

    turns++;
  }

  return state;
}
